[build]
publish = "public"
command = "npm run netlify-build:preview"

[context.production]
command = "npm run netlify-build:production"

[[redirects]]
from = "https://docs.opentelemetry.io/*"
to = "https://opentelemetry.io/docs/:splat"
force = true

[[redirects]]
from = "https://blog.opentelemetry.io/*"
to = "https://opentelemetry.io/blog/:splat"
force = true

[[headers]]
  for = "/schemas/:version"
  [headers.values]
    content-type = "application/yaml"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://widget.kapa.ai https://www.google.com https://code.jquery.com https://unpkg.com https://cdn.jsdelivr.net; connect-src 'self' https://proxy.kapa.ai https://kapa-widget-proxy-la7dkmplpq-uc.a.run.app https://metrics.kapa.ai; frame-src 'self' https://www.google.com; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; img-src 'self' data:"
